pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core 3.1 sdk'
  inputs:
    packageType: sdk
    version: 3.1.100
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: DotNetCoreCLI@2
  displayName: 'Restore Packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'Build test project'
  inputs:
    command: 'build'
    projects: 'Gameboy.VM.Tests/Gameboy.VM.Tests.csproj'
- task: DotNetCoreCLI@2
  displayName: 'Run all integration tests'
  inputs:
    command: 'test'
    projects: 'Gameboy.VM.Tests/Gameboy.VM.Tests.csproj'